export const pages: Record<string, { title: string; eyebrow: string; intro: string; sections: { heading: string; body: string[]; bullets?: string[] }[] }> = {
  "is-pdr-right-for-my-dent": { title: "Is paintless dent repair right for my dent?", eyebrow: "PDR suitability guide", intro: "Paintless dent repair works best when the original finish is intact and the metal can be carefully returned to shape. Photos help, but a hands-on inspection is the reliable way to confirm suitability.", sections: [
    { heading: "Signs your dent may qualify", body: ["Shallow, rounded dents and many ordinary door dings are common PDR candidates. Hail dents may also qualify when paint damage is absent."], bullets: ["Paint is intact without cracking or flaking", "Metal is not severely stretched", "A technician can reach or safely pull the damaged area", "Damage is on a metal body panel rather than broken plastic"] },
    { heading: "When conventional body repair may be better", body: ["PDR is not automatically the right repair for every dent. A provider should be willing to recommend conventional work when it will produce a safer or more complete result."], bullets: ["Paint is cracked, deeply scratched, or missing", "Panel metal is sharply folded or badly stretched", "The panel has previous filler or a poor repaint", "Structural components or safety systems may be involved"] },
    { heading: "How to photograph the damage", body: ["Clean the panel, avoid harsh direct sun, and photograph the dent from several angles. Reflections from a garage opening, parking-lot lines, or a striped object can make the panel distortion easier to see. Include one wider photo showing the panel and one close photo showing the dent."] }
  ]},
  "paintless-dent-repair-cost": { title: "Paintless dent repair cost in Fishers", eyebrow: "Honest pricing guidance", intro: "There is no responsible flat price for a dent that has not been seen. Size matters, but location, access, depth, metal stretch, and total dent count can matter just as much.", sections: [
    { heading: "What changes the price", body: ["A small open-panel dent is usually simpler than a dent on a reinforced body line or beneath trim that must be removed."], bullets: ["Dent diameter, depth, and sharpness", "Panel location and backside access", "Aluminum versus steel panels", "Body-line or edge involvement", "Number and concentration of hail dents", "Required removal and reinstallation of trim or interior panels"] },
    { heading: "Single dents versus hail damage", body: ["Single dents are commonly estimated individually. Hail damage is generally mapped across each affected panel, and an insurer may be involved when a comprehensive claim is opened. Your deductible and policy terms determine insurance coverage—not this website or a repair provider."] },
    { heading: "How to compare estimates", body: ["Ask whether the estimate includes trim removal, taxes, and any expected supplemental work. Confirm who will perform the repair, whether the result is guaranteed, and what happens if PDR cannot safely achieve the expected finish."] }
  ]},
  "how-it-works": { title: "How our Fishers provider-matching service works", eyebrow: "Transparent by design", intro: "Fishers Dent Repair Guide is an independent information and referral website. We are not a body shop and do not represent ourselves as the technician who will repair your vehicle.", sections: [
    { heading: "1. You send a request", body: ["Tell us about the vehicle and damage. Photos can make the first review more useful, but no online assessment is a final repair diagnosis or quote."] },
    { heading: "2. We review and route it", body: ["We check whether the request appears relevant and may share it with one independent provider serving Fishers. Providers are responsible for their own licensing, insurance, workmanship, prices, scheduling, and statements."] },
    { heading: "3. You decide what happens next", body: ["A provider may contact you to ask questions or arrange an inspection. You are not required to hire anyone, and any service agreement is between you and that provider."] },
    { heading: "How this website may be paid", body: ["A participating provider may pay us for advertising, referrals, or qualified leads. That arrangement does not increase your obligation and does not guarantee that a provider is the lowest-priced or only available option."] }
  ]}
};
