import { notFound } from "next/navigation";
import LeadForm from "../../components/LeadForm";
import SiteShell from "../../components/SiteShell";

const services: Record<string, { title: string; intro: string; fit: string; considerations: string[] }> = {
  "hail-damage-repair": { title: "Hail damage repair in Fishers, Indiana", intro: "When hail leaves many shallow dents but the factory finish remains intact, paintless dent repair may restore affected panels without repainting them.", fit: "A technician typically maps dents panel by panel, checks paint condition, identifies access points, and looks for stretched metal or damage that needs conventional repair.", considerations: ["Photograph damage before washing or repairing the vehicle", "Review your comprehensive deductible before opening a claim", "Your insurer—not the repair site—decides coverage", "Avoid anyone who asks you to misstate when or where damage occurred"] },
  "door-ding-repair": { title: "Door ding repair in Fishers, Indiana", intro: "Door dings are among the most common PDR requests. Smooth dents with intact paint are often better candidates than sharp creases at a panel edge.", fit: "Access can require removing safe, non-structural trim or using an exterior glue-pull method. The provider should explain the approach before work begins.", considerations: ["Look closely for paint transfer versus actual paint loss", "Note whether the dent crosses a styling or body line", "Check for previous body filler or repainting", "Ask what result is realistic before authorizing work"] },
  "minor-dent-repair": { title: "Minor dent repair in Fishers, Indiana", intro: "Carts, balls, branches, and everyday accidents can leave repairable dents even when the panel looks dramatic under reflected light.", fit: "The cause matters less than the condition of the metal, paint, and access. A clear photo and accurate size reference can help with an initial review.", considerations: ["Do not push the dent with household tools", "Avoid heating the panel yourself", "Include the whole panel in at least one photo", "Mention sensors, cameras, or trim near the damage"] }
};
export async function generateStaticParams() { return Object.keys(services).map(slug => ({ slug })); }
export default async function ServicePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const s = services[slug]; if (!s) notFound(); return <SiteShell><main><section className="article-hero service"><p className="eyebrow">Fishers paintless dent repair guide</p><h1>{s.title}</h1><p className="lede">{s.intro}</p><a className="button primary" href="#quote">Request a free assessment</a></section><article className="article-body"><section><h2>What a provider will evaluate</h2><p>{s.fit}</p></section><section><h2>Before you request an estimate</h2><ul>{s.considerations.map(x => <li key={x}>{x}</li>)}</ul></section><section><h2>A local referral—not a fake storefront</h2><p>This website does not claim a repair facility or physical address in Fishers. We provide consumer information and may connect your request with an independent provider that serves the area.</p></section></article><section className="section quote-section compact" id="quote"><div className="quote-copy"><p className="eyebrow">Start with the damage</p><h2>Request an initial assessment.</h2><p>A final price requires provider review and may require an in-person inspection.</p></div><LeadForm /></section></main></SiteShell>; }
